# Generated by Django 5.0.6 on 2024-07-06 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('photo', models.ImageField(upload_to='category_photos/')),
                ('brand1_name', models.CharField(max_length=100)),
                ('brand1_items', models.IntegerField()),
                ('brand2_name', models.CharField(max_length=100)),
                ('brand2_items', models.IntegerField()),
            ],
        ),
    ]
