# Generated by Django 5.0.6 on 2024-07-10 16:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_test_alter_category_options'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Test',
        ),
    ]
