# Generated by Django 5.0.6 on 2024-07-11 12:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_delete_test'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'Предмет', 'verbose_name_plural': 'Предметы'},
        ),
        migrations.RemoveField(
            model_name='category',
            name='brand1_items',
        ),
        migrations.RemoveField(
            model_name='category',
            name='brand1_name',
        ),
        migrations.RemoveField(
            model_name='category',
            name='brand2_items',
        ),
        migrations.RemoveField(
            model_name='category',
            name='brand2_name',
        ),
        migrations.RemoveField(
            model_name='category',
            name='photo',
        ),
    ]
