# Generated by Django 5.0.6 on 2024-07-14 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0008_alter_additionalpicture_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='additional_pics',
        ),
        migrations.RemoveField(
            model_name='item',
            name='name',
        ),
        migrations.AddField(
            model_name='item',
            name='additional_pic',
            field=models.ManyToManyField(to='catalog.additionalpicture'),
        ),
    ]
