# Generated by Django 5.0.6 on 2024-07-13 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0009_remove_item_additional_pics_remove_item_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='additional_pic',
            field=models.ManyToManyField(to='catalog.additionalpicture'),
        ),
    ]
