# Generated by Django 5.0.6 on 2024-07-14 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0012_category_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='category_picture',
            field=models.ImageField(default=None, null=True, upload_to='images/category-images/'),
        ),
    ]
