# Generated by Django 5.0.6 on 2024-07-16 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0015_alter_item_category_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='broad_name',
        ),
        migrations.RemoveField(
            model_name='category',
            name='category_name',
        ),
        migrations.AddField(
            model_name='category',
            name='brand_name_1',
            field=models.CharField(default=None, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='category',
            name='brand_name_2',
            field=models.CharField(default=None, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='category',
            name='name',
            field=models.CharField(default=None, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='category',
            name='quantity_1',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='category',
            name='quantity_2',
            field=models.IntegerField(default=1),
        ),
    ]
