# Generated by Django 5.0.6 on 2024-07-16 09:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0016_remove_category_broad_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='brand_name_1',
        ),
        migrations.RemoveField(
            model_name='category',
            name='brand_name_2',
        ),
        migrations.RemoveField(
            model_name='category',
            name='name',
        ),
        migrations.RemoveField(
            model_name='category',
            name='quantity_1',
        ),
        migrations.RemoveField(
            model_name='category',
            name='quantity_2',
        ),
        migrations.AddField(
            model_name='category',
            name='broad_name',
            field=models.CharField(default=models.CharField(default=None, max_length=100, null=True), max_length=100),
        ),
        migrations.AddField(
            model_name='category',
            name='category_name',
            field=models.CharField(default=None, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='category',
            name='slug',
            field=models.SlugField(default=None, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='category_name',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='catalog.category'),
        ),
    ]
